obj-y += an5206.o mcf5208.o

obj-y += mac128k.o iwm.o sy6522.o mac_keyboard.o mac_rtc.o mac_mouse.o z8530.o mac_int_control.o mac_sound_generator.o

obj-y += dummy_m68k.o

obj-y += mcf5206.o mcf_intc.o
