obj-$(CONFIG_SOFTMMU) += replay.o
obj-$(CONFIG_SOFTMMU) += replay-internal.o
obj-$(CONFIG_SOFTMMU) += replay-events.o
obj-$(CONFIG_SOFTMMU) += replay-time.o
obj-$(CONFIG_SOFTMMU) += replay-input.o
obj-$(CONFIG_USER_ONLY) += replay-user.o
